import type { Language } from '../types/sectionKeys'

export type HelpFaqItem = { question: string; answer: string }

export type HelpWorkflowStep = {
  title: string
  paragraphs: string[]
  bullets?: string[]
}

export type HelpComingSoonModule = { name: string }

export type HelpCenterCopy = {
  pageTitle: string
  pageLead: string
  tocLabel: string
  toc: { id: string; label: string }[]
  intro: {
    title: string
    whatIs: { title: string; body: string[] }
    why: { title: string; body: string[] }
    who: { title: string; intro: string; audiences: string[] }
    capabilities: { title: string; items: string[] }
  }
  quickStart: {
    title: string
    intro: string
    steps: string[]
  }
  retrofit: {
    title: string
    purpose: { title: string; body: string[] }
    whenToUse: { title: string; scenarios: string[] }
    workflowTitle: string
    steps: HelpWorkflowStep[]
    reviewTitle: string
    reviewBody: string[]
    reviewOutputs: string[]
  }
  faq: { title: string; items: HelpFaqItem[] }
  tips: { title: string; items: string[] }
  comingSoon: { title: string; intro: string; badge: string; modules: HelpComingSoonModule[] }
}

const comingSoonModules: HelpComingSoonModule[] = [
  { name: 'Resilience Infra Models' },
  { name: 'Design Toolkit' },
  { name: 'Smart Construction' },
  { name: 'Material Hubs' },
  { name: 'Building Codes' },
  { name: 'Best Practices' },
  { name: 'Readiness Calculator' },
  { name: 'Learn & Train' },
  { name: 'Live Earthquake Alerts' },
  { name: 'Disaster Dashboard' },
]

const en: HelpCenterCopy = {
  pageTitle: 'How to Use Infra Resilience360°',
  pageLead:
    'A practical Help Center for Infra Resilience360°. This phase covers the application introduction, quick start, and the complete Retrofit Guide workflow.',
  tocLabel: 'On this page',
  toc: [
    { id: 'help-intro', label: 'Application Introduction' },
    { id: 'help-quick-start', label: 'Quick Start' },
    { id: 'help-retrofit', label: 'Retrofit Guide' },
    { id: 'help-faq', label: 'FAQ' },
    { id: 'help-tips', label: 'Tips' },
    { id: 'help-coming-soon', label: 'Future Modules' },
  ],
  intro: {
    title: 'Application Introduction',
    whatIs: {
      title: 'What is Infra Resilience360°?',
      body: [
        'Infra Resilience360° is an infrastructure safety and disaster engineering toolkit developed to support resilience planning, preparedness, and recovery workflows.',
        'It brings together practical engineering guidance, AI-assisted assessment tools, Pakistan-focused location and rate data, and decision-support modules in one application.',
      ],
    },
    why: {
      title: 'Why it was developed',
      body: [
        'Pakistan faces recurring earthquake, flood, and related infrastructure risks. Field teams, planners, and institutions need faster access to structured guidance, local context, and actionable recommendations.',
        'Infra Resilience360° was developed to reduce fragmentation across guidance, assessment, and planning tools—so users can move from hazard awareness to practical retrofit and resilience decisions with clearer workflow support.',
      ],
    },
    who: {
      title: 'Who should use it',
      intro: 'The application is designed for professionals and institutions involved in infrastructure safety, disaster risk reduction, and resilience planning, including:',
      audiences: [
        'Engineers',
        'Architects',
        'Infrastructure Planners',
        'Government Departments',
        'NDMA',
        'PDMAs',
        'DDMAs',
        'Academia',
        'Students',
        'Disaster Management Professionals',
      ],
    },
    capabilities: {
      title: 'Major capabilities',
      items: [
        'AI-assisted engineering support for image-based defect assessment and retrofit guidance',
        'Infrastructure resilience planning across hazard-aware modules',
        'Decision support for prioritization, scoping, and cost-informed planning',
        'Pakistan-specific resources such as province/city location selection and location-sensitive labour and material rate context',
        'International engineering best practices and training resources available through related modules',
      ],
    },
  },
  quickStart: {
    title: 'Quick Start',
    intro: 'Use this basic workflow to begin working in Infra Resilience360°:',
    steps: [
      'Open Infra Resilience360°.',
      'Select Language from the Menu using Language (PK Urdu or GB English).',
      'Select User Role from the Menu using Role (Engineer / Planner, Contractor / Builder, Homeowner / Resident, or General).',
      'From the Home page, choose the required module card (for this guide: Retrofit Guide).',
      'Follow the module workflow on the selected screen.',
      'View results generated by the module.',
      'Download reports where available (for retrofit costing, use the Retrofit Calculator Final Report path).',
    ],
  },
  retrofit: {
    title: 'Retrofit Guide',
    purpose: {
      title: 'Module Purpose',
      body: [
        'The Retrofit Guide helps you assess existing buildings from defect photographs, generate AI-assisted retrofit guidance for your selected Pakistan location, and continue into location-based cost estimation.',
        'It is designed to support upgrade planning for damaged or vulnerable structures by combining image-based structural observations with recommended retrofit actions and localized cost context.',
      ],
    },
    whenToUse: {
      title: 'When to Use',
      scenarios: [
        'You need image-based retrofit guidance for visible defects (cracks, damage patterns, or structural concerns).',
        'You want recommendations that reflect a selected Pakistan province and city/district for labour and material rate context.',
        'You need to continue from guidance into Retrofit Calculator for detailed estimated retrofit cost, breakdown, and report download.',
        'You are preparing field observations for engineering review, institutional planning, or prioritization discussions.',
      ],
    },
    workflowTitle: 'Step-by-Step Workflow',
    steps: [
      {
        title: 'Step 1 — Open Retrofit Guide',
        paragraphs: [
          'From the Home page, open the Retrofit Guide card (subtitle: Upgrade Existing Structures).',
          'The Retrofit Guide screen appears with the heading 🏠 Retrofit Guide.',
          'You will see the Location for Labor/Material Rates section, the Upload Defect Photos in Series (Image 1, 2, 3...) control, and the action buttons 🛠️ Retrofit Guidance and 🧮 Calculate Retrofit Estimated Cost.',
        ],
      },
      {
        title: 'Step 2 — Set Location for Labor/Material Rates',
        paragraphs: [
          'In Location for Labor/Material Rates, choose how the application should determine your Pakistan location. Location affects labour/material rate context used with guidance and costing workflows.',
        ],
        bullets: [
          '📍 Use My Location — Requests location permission (Allow Location / Enter Manually on native). When allowed, the app detects your city and province and shows an auto-detected location message. While detecting, the button label changes to 📡 Detecting Location....',
          '📍 Enter Location Manually — Shows Province (Pakistan) and City / District (Pakistan) dropdowns. The selected pair appears as Manual Location: City, Province. If auto-detection is unavailable, the app falls back to manual input and may show (Auto-detection unavailable, fallback to manual input).',
          'Default starting location in the module is Lahore / Punjab until you change it.',
        ],
      },
      {
        title: 'Step 3 — Upload Building Defect Images',
        paragraphs: [
          'Use Upload Defect Photos in Series (Image 1, 2, 3...) to add one or more defect photographs.',
          'On web, the file picker accepts image files (image/*) and allows multiple selection. Supported image types processed by the app include JPG/JPEG, PNG, WEBP, HEIC, and HEIF.',
          'On native mobile, Upload Image opens an upload sheet with 📷 Take Photo, 🖼 Choose from Gallery, and Cancel.',
        ],
        bullets: [
          'Selected Photos: shows the count of images currently in the series.',
          'Each uploaded photo appears as an Image N preview card.',
          'Click this photo to add more images — selecting a preview opens the picker again so you can append more photos.',
          'Uploading a new series clears previous guidance/analysis results for a fresh run.',
          'There is no remove-photo control in the Retrofit Guide screen; start a new upload series if you need a clean set.',
        ],
      },
      {
        title: 'Step 4 — Click 🛠️ Retrofit Guidance',
        paragraphs: [
          'After location and photos are ready, click 🛠️ Retrofit Guidance.',
          'While running, the button label changes to 🔄 Analyzing Images + Generating Guidance....',
          'The application analyzes each uploaded image with AI vision services using your selected structure context and Pakistan location/risk profile.',
        ],
        bullets: [
          'If no photos are uploaded, the app prompts: Upload one or more building defect photos before generating guidance.',
          'If province/city are missing, the app prompts: Select a valid Pakistan province and city/district.',
          'Successful runs populate Retrofit Guidance (Image-Based) cards per image, including Summary, Image Visibility, Safety Note, Recommended Guidance, and Detected Damage Features when available.',
          'Structured engineering sections may include: 1) Damage Classification, 2) Severity, 3) Probable Causes, 4) Risk Assessment, 5) Step-by-Step Retrofit Methods, 6) Safety Precautions, and 7) Localized Cost Estimation (with line items and Total Estimated Cost).',
          'If the AI service is unavailable, the app shows a temporary analysis failure message and asks you to try again shortly.',
        ],
      },
      {
        title: 'Step 5 — Click 🧮 Calculate Retrofit Estimated Cost',
        paragraphs: [
          'Click 🧮 Calculate Retrofit Estimated Cost to continue into the Retrofit Calculator (also labeled Retrofit Calculator / Retrofit Pro in the calculator portal).',
          'This button navigates out of the Retrofit Guide into the dedicated cost workflow. Cost estimation, breakdown, and PDF download are completed in Retrofit Calculator.',
        ],
        bullets: [
          'Dashboard → Retrofit Cost Configuration: set location with Use My Current Location or Enter Location Manually, review/edit rates (including Surface Preparation Rate, Epoxy Injection Rate, RC Jacketing Rate, Skilled Labor Rate), then click Confirm Rates & Continue. Use Change Location if you need to revise the city.',
          'Dashboard → AI-Powered Retrofit Assessment: upload a structural defect image with Select Image (or Change Image), then click Start AI Analysis.',
          'Detection Result: review AI Detection Results, confirm structural details, then click Calculate Cost Breakdown.',
          'Cost Breakdown: review Detailed Cost Breakdown, location factors, contingency/overhead, and Total Estimated Cost.',
          'Final Report: review the professional report summary and use Download PDF Report (and Share Summary where available).',
          'Calculator sidebar navigation labels: Dashboard, Detection Result, Cost Breakdown, Final Report.',
        ],
      },
      {
        title: 'Step 6 — Review Generated Results',
        paragraphs: [
          'Return to the Retrofit Guide results area after Step 4 to review guidance outputs before or after cost estimation.',
        ],
      },
    ],
    reviewTitle: 'What to review in Retrofit Guide results',
    reviewBody: [
      'Use the generated cards under Retrofit Guidance (Image-Based) as decision-support material. Always apply engineering judgment before field implementation.',
    ],
    reviewOutputs: [
      'Recommended Guidance — prioritized retrofit actions and methods derived from image analysis',
      'Detected Damage Features — damage type, component, location detail, pattern, crack width range, and estimated extent when returned by analysis',
      'Structural observations — Summary, Image Visibility, Safety Note, severity/risk sections, and step-by-step retrofit methods with materials, tools, and QA checks',
      'Localized Cost Estimation lines inside guidance (when structured guidance is returned)',
      'Downloads/reports — available from Retrofit Calculator Final Report via Download PDF Report after completing the Calculate Retrofit Estimated Cost path',
    ],
  },
  faq: {
    title: 'Retrofit Guide FAQ',
    items: [
      {
        question: 'Which images should I upload?',
        answer:
          'Upload clear photographs of building defects and affected structural elements (for example cracks, damaged walls, columns, beams, or slabs). Include overall context shots and closer views of the defect. The upload control is labeled Upload Defect Photos in Series (Image 1, 2, 3...).',
      },
      {
        question: 'How many images can I upload?',
        answer:
          'The Retrofit Guide accepts multiple images in one series (multiple selection on web; repeated Take Photo / Choose from Gallery on native). Selected Photos shows the current count. The interface does not display a fixed maximum count.',
      },
      {
        question: 'Can I upload multiple images?',
        answer:
          'Yes. Use the multi-file upload control, or click an existing Image N preview (Click this photo to add more images) to append additional photos.',
      },
      {
        question: 'What image formats are supported?',
        answer:
          'The upload control accepts image files (image/*). The application processes common formats including JPG/JPEG, PNG, WEBP, HEIC, and HEIF.',
      },
      {
        question: 'How does location affect labour and material rates?',
        answer:
          'Location for Labor/Material Rates uses either 📍 Use My Location or 📍 Enter Location Manually (Province / City-District). The selected Pakistan city and province drive location-sensitive rate context used with retrofit guidance and the Retrofit Calculator costing workflow.',
      },
      {
        question: 'How does AI analyze damage?',
        answer:
          'When you click 🛠️ Retrofit Guidance, each uploaded image is sent for AI vision analysis with your location and risk profile. The app returns per-image summaries, safety notes, recommended guidance, detected damage features, and structured sections such as damage classification, severity, causes, risk, retrofit methods, safety precautions, and localized cost lines when available.',
      },
      {
        question: 'How is retrofit cost estimated?',
        answer:
          'From Retrofit Guide, click 🧮 Calculate Retrofit Estimated Cost to open Retrofit Calculator. Confirm location rates (Confirm Rates & Continue), upload an image, run Start AI Analysis, confirm detection details, then Calculate Cost Breakdown. The Cost Breakdown and Final Report pages present estimated costs using confirmed rates, location factors, and analysis outputs.',
      },
      {
        question: 'Can I download the report?',
        answer:
          'Yes, after completing the Retrofit Calculator workflow through Final Report, use Download PDF Report. Share Summary is also available on that page.',
      },
      {
        question: 'What happens if AI analysis fails?',
        answer:
          'If analysis cannot complete, Retrofit Guide shows a temporary unavailability message and asks you to try again shortly. In Retrofit Calculator, analysis errors also provide retry guidance on the assessment screen.',
      },
      {
        question: 'Does Retrofit Guidance replace a professional engineering assessment?',
        answer:
          'No. AI-assisted outputs are decision-support information. Verify recommendations and cost estimates through qualified engineering assessment before implementation.',
      },
    ],
  },
  tips: {
    title: 'Practical Tips',
    items: [
      'Upload clear, high-resolution images with adequate lighting.',
      'Capture defects from multiple angles so severity and extent are easier to interpret.',
      'Include both overall views of the element and close-up views of the defect.',
      'Confirm Province (Pakistan) and City / District (Pakistan) before generating guidance so labour/material rate context is correct.',
      'Review AI guidance carefully under Recommended Guidance and structured sections before making engineering decisions.',
      'Use 🧮 Calculate Retrofit Estimated Cost when you need a full cost breakdown and PDF report through Retrofit Calculator.',
      'Verify generated estimates through independent engineering assessment where necessary.',
    ],
  },
  comingSoon: {
    title: 'Future Module Guides',
    intro: 'Additional module guides will be added in later phases. The following modules are listed as Coming Soon in this Help Center:',
    badge: 'Coming Soon',
    modules: comingSoonModules,
  },
}

const ur: HelpCenterCopy = {
  pageTitle: 'Infra Resilience360° کیسے استعمال کریں',
  pageLead:
    'Infra Resilience360° کے لیے عملی ہیلپ سینٹر۔ اس مرحلے میں ایپلیکیشن تعارف، فوری آغاز، اور مکمل Retrofit Guide ورک فلو شامل ہے۔',
  tocLabel: 'اس صفحے پر',
  toc: [
    { id: 'help-intro', label: 'ایپلیکیشن تعارف' },
    { id: 'help-quick-start', label: 'فوری آغاز' },
    { id: 'help-retrofit', label: 'Retrofit Guide' },
    { id: 'help-faq', label: 'عمومی سوالات' },
    { id: 'help-tips', label: 'مشورے' },
    { id: 'help-coming-soon', label: 'آئندہ ماڈیولز' },
  ],
  intro: {
    title: 'ایپلیکیشن تعارف',
    whatIs: {
      title: 'Infra Resilience360° کیا ہے؟',
      body: [
        'Infra Resilience360° ایک بنیادی ڈھانچے کی حفاظت اور آفات سے متعلق انجینئرنگ ٹول کٹ ہے جو لچکدار منصوبہ بندی، تیاری، اور بحالی کے ورک فلوز کی معاونت کے لیے تیار کی گئی ہے۔',
        'یہ عملی انجینئرنگ رہنمائی، مصنوعی ذہانت کی مدد سے تشخیص، پاکستان پر مرکوز مقام اور شرح کے ڈیٹا، اور فیصلہ سازی کے ماڈیولز کو ایک ایپ میں یکجا کرتی ہے۔',
      ],
    },
    why: {
      title: 'یہ کیوں تیار کی گئی',
      body: [
        'پاکستان زلزلہ، سیلاب، اور متعلقہ بنیادی ڈھانچے کے خطرات کا سامنا کرتا ہے۔ فیلڈ ٹیموں، منصوبہ سازوں، اور اداروں کو منظم رہنمائی، مقامی سیاق، اور قابلِ عمل سفارشات تک تیز رسائی درکار ہوتی ہے۔',
        'Infra Resilience360° اس لیے تیار کی گئی تاکہ رہنمائی، تشخیص، اور منصوبہ بندی کے اوزار بکھرے نہ رہیں—اور صارفین خطرے کی آگاہی سے عملی ریٹروفٹ اور لچکدار فیصلوں تک واضح ورک فلو کے ساتھ پہنچ سکیں۔',
      ],
    },
    who: {
      title: 'کون استعمال کرے',
      intro: 'یہ ایپلیکیشن بنیادی ڈھانچے کی حفاظت، آفات کے خطرے میں کمی، اور لچکدار منصوبہ بندی سے وابستہ پیشہ ور افراد اور اداروں کے لیے ہے، بشمول:',
      audiences: [
        'انجینئرز',
        'آرکیٹیکٹس',
        'انفراسٹرکچر پلانرز',
        'حکومتی محکمے',
        'NDMA',
        'PDMAs',
        'DDMAs',
        'academia / علمی ادارے',
        'طلبہ',
        'ڈزاسٹر مینجمنٹ پیشہ ور',
      ],
    },
    capabilities: {
      title: 'اہم صلاحیتیں',
      items: [
        'تصویری نقص کی تشخیص اور ریٹروفٹ رہنمائی کے لیے مصنوعی ذہانت کی مدد',
        'خطرہ آگاہ ماڈیولز کے ذریعے بنیادی ڈھانچے کی لچکدار منصوبہ بندی',
        'ترجیح، دائرہ کار، اور لاگت پر مبنی فیصلہ سازی کی معاونت',
        'پاکستان مخصوص وسائل جیسے صوبہ/شہر انتخاب اور مزدوری و مواد کی شرح کا سیاق',
        'متعلقہ ماڈیولز کے ذریعے بین الاقوامی بہترین طریقے اور تربیتی وسائل',
      ],
    },
  },
  quickStart: {
    title: 'فوری آغاز',
    intro: 'Infra Resilience360° میں کام شروع کرنے کے لیے یہ بنیادی ورک فلو استعمال کریں:',
    steps: [
      'Infra Resilience360° کھولیں۔',
      'مینو سے Language منتخب کریں (PK Urdu یا GB English)۔',
      'مینو سے Role منتخب کریں (Engineer / Planner، Contractor / Builder، Homeowner / Resident، یا General)۔',
      'مرکزی صفحے سے مطلوبہ ماڈیول کارڈ منتخب کریں (اس گائیڈ کے لیے: Retrofit Guide)۔',
      'منتخب اسکرین پر ماڈیول ورک فلو پر عمل کریں۔',
      'ماڈیول کے تیار کردہ نتائج دیکھیں۔',
      'جہاں دستیاب ہو رپورٹ ڈاؤن لوڈ کریں (ریٹروفٹ لاگت کے لیے Retrofit Calculator کے Final Report راستے کا استعمال کریں)۔',
    ],
  },
  retrofit: {
    title: 'Retrofit Guide',
    purpose: {
      title: 'ماڈیول کا مقصد',
      body: [
        'Retrofit Guide آپ کو نقص کی تصاویر سے موجودہ عمارتوں کا جائزہ لینے، منتخب پاکستانی مقام کے مطابق مصنوعی ذہانت کی مدد سے ریٹروفٹ رہنمائی حاصل کرنے، اور مقام پر مبنی لاگت کے تخمینے تک آگے بڑھنے میں مدد دیتا ہے۔',
        'یہ خراب یا کمزور ڈھانچوں کی اپ گریڈ منصوبہ بندی کے لیے تصویری مشاہدات، تجویز کردہ ریٹروفٹ اقدامات، اور مقامی لاگت کے سیاق کو یکجا کرتا ہے۔',
      ],
    },
    whenToUse: {
      title: 'کب استعمال کریں',
      scenarios: [
        'جب آپ کو ظاہری نقائص (دراڑیں، نقص کے نمونے، یا ساختی خدشات) کے لیے تصویری ریٹروفٹ رہنمائی درکار ہو۔',
        'جب آپ ایسی سفارشات چاہتے ہوں جو پاکستان کے منتخب صوبے اور شہر/ضلع کی مزدوری و مواد کی شرح کے سیاق سے ہم آہنگ ہوں۔',
        'جب آپ رہنمائی کے بعد Retrofit Calculator میں تفصیلی لاگت، بریک ڈاؤن، اور رپورٹ ڈاؤن لوڈ تک جانا چاہتے ہوں۔',
        'جب آپ فیلڈ مشاہدات کو انجینئرنگ جائزے، ادارہ جاتی منصوبہ بندی، یا ترجیحی مباحثے کے لیے تیار کر رہے ہوں۔',
      ],
    },
    workflowTitle: 'قدم بہ قدم ورک فلو',
    steps: [
      {
        title: 'قدم 1 — Retrofit Guide کھولیں',
        paragraphs: [
          'مرکزی صفحے سے Retrofit Guide کارڈ کھولیں (سب ٹائٹل: Upgrade Existing Structures)۔',
          'اسکرین پر عنوان 🏠 Retrofit Guide ظاہر ہوتا ہے۔',
          'آپ Location for Labor/Material Rates سیکشن، Upload Defect Photos in Series (Image 1, 2, 3...) کنٹرول، اور بٹن 🛠️ Retrofit Guidance اور 🧮 Calculate Retrofit Estimated Cost دیکھیں گے۔',
        ],
      },
      {
        title: 'قدم 2 — مزدوری/مواد کی شرح کے لیے مقام طے کریں',
        paragraphs: [
          'Location for Labor/Material Rates میں منتخب کریں کہ ایپ آپ کا پاکستانی مقام کیسے طے کرے۔ مقام رہنمائی اور لاگت کے ورک فلو میں مزدوری/مواد کی شرح کے سیاق کو متاثر کرتا ہے۔',
        ],
        bullets: [
          '📍 Use My Location — مقام کی اجازت مانگتا ہے (Allow Location / Enter Manually)۔ اجازت پر شہر و صوبہ خود کار شناخت ہوتے ہیں۔ شناخت کے دوران بٹن 📡 Detecting Location... دکھاتا ہے۔',
          '📍 Enter Location Manually — Province (Pakistan) اور City / District (Pakistan) ڈراپ ڈاؤن دکھاتا ہے۔ منتخب جوڑی Manual Location: City, Province کے طور پر نظر آتی ہے۔',
          'ماڈیول کا ڈیفالٹ مقام Lahore / Punjab ہے جب تک آپ اسے تبدیل نہ کریں۔',
        ],
      },
      {
        title: 'قدم 3 — عمارت کے نقص کی تصاویر اپ لوڈ کریں',
        paragraphs: [
          'Upload Defect Photos in Series (Image 1, 2, 3...) سے ایک یا زیادہ تصاویر شامل کریں۔',
          'ویب پر فائل منتخب کنندہ image/* قبول کرتا ہے اور متعدد انتخاب کی اجازت دیتا ہے۔ معاون فارمیٹس میں JPG/JPEG، PNG، WEBP، HEIC، اور HEIF شامل ہیں۔',
          'نیٹو موبائل پر Upload Image شیٹ کھولتی ہے: 📷 Take Photo، 🖼 Choose from Gallery، اور Cancel۔',
        ],
        bullets: [
          'Selected Photos: موجودہ سیریز میں تصاویر کی تعداد دکھاتا ہے۔',
          'ہر تصویر Image N پری ویو کارڈ کے طور پر نظر آتی ہے۔',
          'Click this photo to add more images — مزید تصاویر شامل کرنے کے لیے۔',
          'نئی اپ لوڈ پچھلے guidance/analysis نتائج صاف کر دیتی ہے۔',
          'Retrofit Guide میں تصویر ہٹانے کا الگ کنٹرول نہیں ہے؛ نئی سیریز سے دوبارہ شروع کریں۔',
        ],
      },
      {
        title: 'قدم 4 — 🛠️ Retrofit Guidance پر کلک کریں',
        paragraphs: [
          'مقام اور تصاویر تیار ہونے کے بعد 🛠️ Retrofit Guidance دبائیں۔',
          'چلتے وقت بٹن 🔄 Analyzing Images + Generating Guidance... دکھاتا ہے۔',
          'ایپ ہر تصویر کا مصنوعی ذہانت سے تجزیہ کرتی ہے اور مقام/خطرے کے پروفائل کے ساتھ رہنمائی تیار کرتی ہے۔',
        ],
        bullets: [
          'بغیر تصاویر کے پیغام: Upload one or more building defect photos before generating guidance.',
          'بغیر صوبہ/شہر کے پیغام: Select a valid Pakistan province and city/district.',
          'کامیاب نتائج Retrofit Guidance (Image-Based) کارڈز میں Summary، Image Visibility، Safety Note، Recommended Guidance، اور Detected Damage Features دکھاتے ہیں۔',
          'ساختہ سیکشنز میں Damage Classification، Severity، Probable Causes، Risk Assessment، Step-by-Step Retrofit Methods، Safety Precautions، اور Localized Cost Estimation شامل ہو سکتے ہیں۔',
          'سروس دستیاب نہ ہو تو عارضی ناکامی کا پیغام آتا ہے اور دوبارہ کوشش کی ہدایت ملتی ہے۔',
        ],
      },
      {
        title: 'قدم 5 — 🧮 Calculate Retrofit Estimated Cost پر کلک کریں',
        paragraphs: [
          '🧮 Calculate Retrofit Estimated Cost دبانے سے Retrofit Calculator (Retrofit Pro) کھلتا ہے۔',
          'لاگت کا تخمینہ، بریک ڈاؤن، اور PDF ڈاؤن لوڈ Retrofit Calculator میں مکمل ہوتے ہیں۔',
        ],
        bullets: [
          'Dashboard → Retrofit Cost Configuration: Use My Current Location یا Enter Location Manually، شرحیں دیکھیں/ترمیم کریں، پھر Confirm Rates & Continue۔',
          'Dashboard → AI-Powered Retrofit Assessment: Select Image / Change Image، پھر Start AI Analysis۔',
          'Detection Result: تفصیلات تصدیق کریں، پھر Calculate Cost Breakdown۔',
          'Cost Breakdown: Detailed Cost Breakdown اور Total Estimated Cost کا جائزہ لیں۔',
          'Final Report: Download PDF Report (اور Share Summary جہاں دستیاب ہو)۔',
          'سائڈ بار: Dashboard، Detection Result، Cost Breakdown، Final Report۔',
        ],
      },
      {
        title: 'قدم 6 — تیار کردہ نتائج کا جائزہ لیں',
        paragraphs: [
          'قدم 4 کے بعد Retrofit Guide کے نتائج کا جائزہ لیں، لاگت کے تخمینے سے پہلے یا بعد۔',
        ],
      },
    ],
    reviewTitle: 'Retrofit Guide نتائج میں کیا دیکھیں',
    reviewBody: [
      'Retrofit Guidance (Image-Based) کے کارڈز فیصلہ سازی کی معاونت ہیں۔ فیلڈ عمل سے پہلے انجینئرنگ فیصلہ لازمی ہے۔',
    ],
    reviewOutputs: [
      'Recommended Guidance — تصویری تجزیے سے حاصل ترجیحی اقدامات',
      'Detected Damage Features — نقص کی قسم، جزو، مقام، نمونہ، دراڑ کی چوڑائی، اور اندازاً وسعت',
      'ساختی مشاہدات — Summary، Safety Note، شدت/خطرہ، اور مرحلہ وار طریقے مع مواد، اوزار، اور QA',
      'Localized Cost Estimation کی لائنیں (جب ساختہ رہنمائی دستیاب ہو)',
      'ڈاؤن لوڈز/رپورٹس — Calculate Retrofit Estimated Cost کے بعد Final Report میں Download PDF Report',
    ],
  },
  faq: {
    title: 'Retrofit Guide عمومی سوالات',
    items: [
      {
        question: 'کون سی تصاویر اپ لوڈ کروں؟',
        answer:
          'عمارت کے نقائص اور متاثرہ ساختی اجزاء کی واضح تصاویر اپ لوڈ کریں۔ مجموعی اور قریبی دونوں مناظر شامل کریں۔ کنٹرول کا نام Upload Defect Photos in Series (Image 1, 2, 3...) ہے۔',
      },
      {
        question: 'کتنی تصاویر اپ لوڈ کر سکتا/سکتی ہوں؟',
        answer:
          'Retrofit Guide ایک سیریز میں متعدد تصاویر قبول کرتا ہے۔ Selected Photos موجودہ تعداد دکھاتا ہے۔ انٹرفیس میں مقررہ زیادہ سے زیادہ حد ظاہر نہیں ہوتی۔',
      },
      {
        question: 'کیا متعدد تصاویر اپ لوڈ کر سکتا/سکتی ہوں؟',
        answer:
          'ہاں۔ متعدد فائل انتخاب استعمال کریں، یا Image N پری ویو پر کلک کر کے مزید تصاویر شامل کریں (Click this photo to add more images)۔',
      },
      {
        question: 'کون سے تصویری فارمیٹ معاون ہیں؟',
        answer:
          'اپ لوڈ image/* قبول کرتا ہے۔ ایپ عام فارمیٹس جیسے JPG/JPEG، PNG، WEBP، HEIC، اور HEIF پر کارروائی کرتی ہے۔',
      },
      {
        question: 'مقام مزدوری اور مواد کی شرح کو کیسے متاثر کرتا ہے؟',
        answer:
          'Location for Labor/Material Rates میں 📍 Use My Location یا 📍 Enter Location Manually سے منتخب پاکستانی شہر/صوبہ رہنمائی اور Retrofit Calculator لاگت کے سیاق کو طے کرتا ہے۔',
      },
      {
        question: 'مصنوعی ذہانت نقص کا تجزیہ کیسے کرتی ہے؟',
        answer:
          '🛠️ Retrofit Guidance پر کلک کرنے سے ہر تصویر کا تجزیہ ہوتا ہے اور Summary، Safety Note، Recommended Guidance، Detected Damage Features، اور ساختہ سیکشنز واپس آتے ہیں۔',
      },
      {
        question: 'ریٹروفٹ لاگت کا تخمینہ کیسے لگتا ہے؟',
        answer:
          '🧮 Calculate Retrofit Estimated Cost سے Retrofit Calculator کھولیں، Confirm Rates & Continue کریں، تصویر اپ لوڈ کر کے Start AI Analysis چلائیں، پھر Calculate Cost Breakdown اور Final Report دیکھیں۔',
      },
      {
        question: 'کیا رپورٹ ڈاؤن لوڈ کر سکتا/سکتی ہوں؟',
        answer:
          'ہاں۔ Retrofit Calculator کے Final Report میں Download PDF Report استعمال کریں۔ Share Summary بھی دستیاب ہو سکتا ہے۔',
      },
      {
        question: 'اگر مصنوعی ذہانت کا تجزیہ ناکام ہو جائے تو؟',
        answer:
          'عارضی عدم دستیابی کا پیغام آتا ہے؛ تھوڑی دیر بعد دوبارہ کوشش کریں۔ Calculator میں بھی retry کی ہدایت ملتی ہے۔',
      },
      {
        question: 'کیا Retrofit Guidance پیشہ ورانہ انجینئرنگ جائزے کی جگہ لے سکتی ہے؟',
        answer:
          'نہیں۔ مصنوعی ذہانت کی مدد سے نتائج فیصلہ سازی کی معاونت ہیں۔ عمل سے پہلے اہل انجینئرنگ جائزہ ضروری ہے۔',
      },
    ],
  },
  tips: {
    title: 'عملی مشورے',
    items: [
      'واضح، اعلیٰ معیار کی تصاویر اپ لوڈ کریں۔',
      'نقص کو متعدد زاویوں سے کیپچر کریں۔',
      'مجموعی اور قریبی دونوں مناظر شامل کریں۔',
      'رہنمائی سے پہلے Province (Pakistan) اور City / District (Pakistan) درست کریں۔',
      'Recommended Guidance اور ساختہ سیکشنز کا احتیاط سے جائزہ لیں۔',
      'مکمل لاگت اور PDF کے لیے 🧮 Calculate Retrofit Estimated Cost استعمال کریں۔',
      'جہاں ضروری ہو تخمینوں کی آزاد انجینئرنگ تصدیق کریں۔',
    ],
  },
  comingSoon: {
    title: 'آئندہ ماڈیول گائیڈز',
    intro: 'باقی ماڈیول گائیڈز بعد کے مراحل میں شامل ہوں گی۔ اس ہیلپ سینٹر میں درج ذیل Coming Soon ہیں:',
    badge: 'Coming Soon',
    modules: comingSoonModules,
  },
}

export function getHelpCenterCopy(language: Language): HelpCenterCopy {
  return language === 'ur' ? ur : en
}
